import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import Header from '../app/components/header'
import Footer from '../app/components/footer'
import { QueryClient} from '@tanstack/react-query'
import QueryClientProvider from '@/provider/query-client'
export const metadata = {
  title: 'Woodland Interiors',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <Header />
          <main className='main-content'>{children}</main>
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  )
}
