import { ROBOTO, CRIMSON } from "./fonts";
import Header from "../app/components/header";
import Footer from "../app/components/footer";
import { QueryClient } from "@tanstack/react-query";
import QueryClientProvider from "@/provider/query-client";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
export const metadata = {
  title: "Woodland Interiors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body className={`${CRIMSON.variable} ${ROBOTO.variable}`}>
        <QueryClientProvider>
          <Header />
          <main className="main-content">{children}</main>
          <Footer />
        </QueryClientProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
